---
include:
  # Dongle builds
  - board: nice_nano_v2
    shield: imprint_dongle dongle_display
    artifact-name: imprint_dongle
  - board: assimilator-bt
    shield: imprint_dongle_left
    artifact-name: imprint_dongle_left
  - board: assimilator-bt
    shield: imprint_dongle_right
    artifact-name: imprint_dongle_right
  # Settings reset — flash to ALL devices before initial pairing.
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_dongle
    cmake-args: -DCONFIG_ZMK_RGB_UNDERGLOW=n
  - board: assimilator-bt
    shield: settings_reset_peripheral
    artifact-name: settings_reset_peripheral
