---
include:
  # Original non-dongle builds (fallback)
  - board: assimilator-bt
    shield: imprint_left
  - board: assimilator-bt
    shield: imprint_right
  # Dongle builds
  - board: nice_nano
    shield: imprint_dongle
    artifact-name: imprint_dongle
  - board: assimilator-bt
    shield: imprint_dongle_left
    artifact-name: imprint_dongle_left
  - board: assimilator-bt
    shield: imprint_dongle_right
    artifact-name: imprint_dongle_right
  # Settings reset — flash to dongle before initial pairing.
  # For the halves, use &bt BT_CLR_ALL from the keymap instead.
  # (assimilator-bt settings_reset fails: upstream board DTS references
  #  spi1_default pinctrl that only the imprint shield overlay provides.)
  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset_dongle
    cmake-args: -DCONFIG_ZMK_RGB_UNDERGLOW=n
