---
include:
  # Original non-dongle builds (fallback)
  - board: assimilator-bt
    shield: imprint_left
  - board: assimilator-bt
    shield: imprint_right
  # Dongle builds
  - board: nice_nano_v2
    shield: imprint_dongle
    artifact-name: imprint_dongle
  - board: assimilator-bt
    shield: imprint_dongle_left
    artifact-name: imprint_dongle_left
  - board: assimilator-bt
    shield: imprint_dongle_right
    artifact-name: imprint_dongle_right
  # Settings reset (flash to all 3 devices before initial pairing)
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_dongle
  - board: assimilator-bt
    shield: settings_reset
    artifact-name: settings_reset_assimilator
