# Left peripheral: RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
# Pink (old default)
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=343
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=69
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50

# Orange (matching zmk-new_corne)
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=30
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50

# No display on peripherals (override base conf)
CONFIG_ZMK_DISPLAY=n
