manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Cyboard-DigitalTailor
      url-base: https://github.com/Cyboard-DigitalTailor
    - name: david-lai-jpg
      url-base: https://github.com/david-lai-jpg
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-keyboards
      remote: Cyboard-DigitalTailor
      revision: studio-support
      import: config/west.yml
    - name: zmk-acceleration-curves
      remote: david-lai-jpg
      revision: default-curve
  self:
    path: config
